---
# tasks file for phy_kernel
- name: Create a directory if it does not exist
  file:
    path: "{{ deployDir }}/kernel"
    state: directory

- name: copy files from local to remote
  copy:
    src: files/
    dest: "{{ deployDir }}/kernel"
- name: update kernel
  shell: cd "{{ deployDir }}/kernel";chmod +x *.sh ; ./update_kernel.sh
  register: shell_result    
    
- debug:    
    msg: "{{shell_result.stdout_lines}}"  
