


# - hosts: hangzhou-test
#   tasks:
#     - name: create log file
#       file: name=/home/hangzhou/{{ ansible_test }} state=touch


# '''
# 复制远程文件
- hosts: hangzhouvm
  remote_user: sfdev
  gather_facts: no
  vars:
    abe: 100
  tasks: 
    # - name: copy log file
    #   copy: src=/home/sfdev/hangz/shellLearn/HugePages.sh dest=/home/sfdev/hang/
    # - name: run shell
    #   shell: cd /home/sfdev/hang; chmod +x *.sh; ./HugePages.sh 3 1048576

    # - shell: echo {{ abe }} #true
    # - shell: echo {{abe}} #true
    # - shell: echo "{{ abe }}" #true
    # - shell: echo "{{abe}}" #true
    - name: dect aa 
      shell: . /etc/os-release; echo $PWD #false
        # cmd: echo {{ abe }} #false
        # cmd: ". /etc/os-release; echo $ID" #false
      register: return_value
      ignore_errors: true
      # msg: return_valu

    - name: get HugePages_Total
      shell: grep HugePages_Total /proc/meminfo | awk '{print $2}'
      register: HugePages_Total

      
    - name: test vars and when
      shell: "ls -ahl"
      when: "{{ HugePages_Total | int }} < {{ abe }}" #true
      # when: "{{ HugePages_Total | int }} < {{abe}}" true
      # when: "{{ HugePages_Total | int }} < abe" #true
      # when: HugePages_Total.stdout | int < abe #true
      # when: HugePages_Total.stdout < abe #false
      register: testwhen
    - debug:
        msg: "{{testwhen}}"
    - debug:
        # msg: "{{ return_value }}" ## true
        msg: "{{return_value}}" ## true
    - debug: 
        msg: "{{ HugePages_Total }}"
        # msg: {{ return_value }} ## false
        # msg: {{return_value}} ## false



    # - name: copy shell file
    #   script: /home/sfdev/hangz/shellLearn/HugePages.sh 2 2048


      # copy: src=/home/sfdev/hangz/shellLearn/HugePages.sh dest=/home/sfdev/hang

# '''

