---
# tasks file for phy_Hugepages

    

# - name: copy script file
#   copy: src=HugePages.sh dest=/home/sfdev/hang/
# - name: run shell
#   shell: cd /home/sfdev/hang; chmod +x *.sh; ./HugePages.sh 3 4096

# - debug:    
#     msg: "{{shell_result.stdout_lines}}"  


- name: get HugePages_Total
  shell: grep HugePages_Total /proc/meminfo | awk '{print $2}'
  register: HugePages_Total

- name: get Hugepagesize
  shell: grep Hugepagesize /proc/meminfo | awk '{print $2}'
  register: Hugepagesize

- name: get HugePages_Free
  shell: grep HugePages_Free /proc/meminfo | awk '{print $2}'
  register: HugePages_Free



- name: Change Hugepages when conditions are met
  shell: sudo grubby --update-kernel=DEFAULT --args="default_hugepagesz={{ Required_Size }}kB hugpagesz={{ Required_Size }}kB hugepages={{ Required_HugePage }}" && reboot
  when:  "{{ Hugepagesize | int }}  != {{ Required_Size }} or {{ HugePages_Total | int }} < {{ Required_Size }}"


- name: Change Hugepages when conditions are met
  shell:  reboot
  when: "{{ HugePages_Free | int }} < {{ Required_HugePage }}"