FROM openvino/ubuntu18_dev:2021.4
USER root

RUN apt-get update && \
    apt-get install -y \
    build-essential \
    numactl


RUN cd inference_engine/samples/cpp/ && \
         ./build_samples.sh

