- name: Stat of remote
  stat:
    path: "{{vars_jenkins_home}}/plugins/{{item.vars_plugin_name}}"
  loop: "{{ vars_plugin_files}}"
  register: file_stat


- debug:
    msg: "{{file_stat}}"


- debug:
    msg: "{{vars_plugin_files|zip(file_stat.results)}}"

- debug:
    msg: "{{vars_plugin_files|zip(file_stat.results)|list}}"

# - debug:
#     msg: "{{file_stat.s }}"

# - name: Debug the result of the comparision
#   debug:
#     msg: "The local file -> {{ item.0.vars_plugin_name }} with the checksum (WROTTEN AS VAR ON THE FILE) {{ item.0.vars_plugin_checksum }}  And the remote file {{item.1.stat.path}} with  Checksum -> {{ item.1.stat.checksum}}"
#   loop: "{{vars_plugin_files|zip(file_stat.results)|list}}"
#   failed_when: "item.0.vars_plugin_checksum not in  item.1.stat.checksum"