---

- name: Determine whether has been loaded
  shell: |
    lsmod | grep dlb
  register: dlb_loaded
  ignore_errors: true

- debug:
    msg: "dlb is loaded on this machine"
  when: dlb_loaded.stdout != ""

- block:
    - name: install kernel module
      shell: |
        modprobe dlb2
      register: kernel_dlb_installed
      ignore_errors: true

    - debug:
        msg: "{{kernel_dlb_installed}}"

    - debug:
        msg: "no kernel dlb driver"
      when: "'not found' in kernel_dlb_installed.stderr"
  when: dlb_loaded.stdout == ""

- block:
    - name: judge DLB lists
      shell: lspci | grep 2710
      register: dlb_supported
      ignore_errors: true

    - debug:
        msg: "This machine does not support dlb"
      when: dlb_supported is failed
      
    - block:
      - setup:

      - name: install dependencies
        include_role:
          name: install_dependencies

      - name: download dlb_zip
        get_url:
          url: "{{dlb_zip_url}}"
          dest: /usr/local/src
          mode: 0644
          force: yes 
        ignore_errors: true
        delegate_to: localhost

      - name: unzip dlb_zip
        unarchive:
          src: "/usr/local/src/{{dlb_zip}}"
          dest: /home/raspadmin
          copy: yes
          mode: 0755
        ignore_errors: true

      - name: install dlb driver
        shell: 
          cmd: |
            make
            modprobe vfio-pci
            modprobe mdev
            insmod dlb2.ko
          executable: /bin/bash
        args:
          chdir: dlb/driver/dlb2
        ignore_errors: true
      when: dlb_supported is success
  when:
    - dlb_loaded.stdout == ""
    - "'not found' in kernel_dlb_installed.stderr"