# BIOS_CONFIG: [
#   {"knob":"ProcessorX2apic" , "prompt": "Enable/disable extended APIC support", "value": "0x0"},
#   {"knob":"VTdSupport" , "prompt": "Intel(R) VT for Directed I/O", "value": "0x0"},
#   {"knob": "TurboMode", "prompt": "Intel(R) Turbo Boost Technology", "value": "0x0"},
#   {"knob": "ProcessorHyperThreadingDisable", "prompt": "Intel(R) Hyper-Threading Tech", "value": "0x00"},
#   {"knob": "SncEn", "prompt": "SNC (Sub NUMA)", "value": "0x04"},
#   {"knob": "PcieEnqCmdSupport", "prompt": "PCIe ENQCMD/ENQCMDS", "value": "0x00"}
# ]





# gama: 0.001
# sigma: 8.5

BIOS_CONFIG: [
  {"knob": "TurboMode", "prompt": "Intel(R) Turbo Boost Technology", "value": "0x0"},
  {"knob": "ProcessorHyperThreadingDisable", "value": "0x01"},
  {"knob": "SncEn", "prompt": "SNCdafdsfa (Sub NUMA)", "value": "0x04"},
]