


# - hosts: hangzhou-test
#   tasks:
#     - name: create log file
#       file: name=/home/hangzhou/{{ ansible_test }} state=touch


# '''
# 复制远程文件
# - hosts: hangzhouvm
#   remote_user: sfdev
#   gather_facts: no
#   vars:
#     abe: 100
#   tasks: 

#     # - name: copy log file
#     #   copy: src=/home/sfdev/hangz/shellLearn/HugePages.sh dest=/home/sfdev/hang/
#     # - name: run shell
#     #   shell: cd /home/sfdev/hang; chmod +x *.sh; ./HugePages.sh 3 1048576

#     # - shell: echo {{ abe }} #true
#     # - shell: echo {{abe}} #true
#     # - shell: echo "{{ abe }}" #true
#     # - shell: echo "{{abe}}" #true
#     - name: dect aa 
#       shell: . /etc/os-release; echo $PWD #false
#         # cmd: echo {{ abe }} #false
#         # cmd: ". /etc/os-release; echo $ID" #false
#       register: return_value
#       ignore_errors: true
#       # msg: return_valu

#     - name: get HugePages_Total
#       shell: grep HugePages_Total /proc/meminfo | awk '{print $2}'
#       register: HugePages_Total

      
#     - name: test vars and when
#       shell: "ls -ahl"
#       when: "{{ HugePages_Total | int }} < {{ abe }}" #true
#       # when: "{{ HugePages_Total | int }} < {{abe}}" true
#       # when: "{{ HugePages_Total | int }} < abe" #true
#       # when: HugePages_Total.stdout | int < abe #true
#       # when: HugePages_Total.stdout < abe #false
#       register: testwhen
#     - debug:
#         msg: "{{testwhen}}"
#     - debug:
#         # msg: "{{ return_value }}" ## true
#         msg: "{{return_value}}" ## true
#     - debug: 
#         msg: "{{ HugePages_Total }}"
#         # msg: {{ return_value }} ## false
#         # msg: {{return_value}} ## false





# - hosts: biostest
#   remote_user: sfdev
#   gather_facts: true
#   vars:
#     abe: 100
#     users: 
#       alice: female 
#       bob: male
#   tasks: 
#     - debug:
#         msg: "{{item.key}} is {{item.value}}"
#       # with_dict: "{{users}}"
#       loop: "{{lookup('dict',users)}}"
#       when: ansible_distribution_version <= "8"




---

- hosts: 10.219.170.236
# - hosts: localhost
# - hosts: ICX_junjunjie
  become: yes
  gather_facts: no

  vars:
    dlb_zip_url: https://af01p-igk.devtools.intel.com/artifactory/platform_hero-igk-local/dlb_release_ver_7.5.0.zip
    dlb_zip: dlb_release_ver_7.5.0.zip
    qat_firmware_repo: https://af01p-igk.devtools.intel.com/artifactory/platform_hero-igk-local/benchmark_test_result/pool/qatfirmware.tar
    repos:
      - name: repo1
        os_list:
          - centos
          - rhel
        major_distribution_list:
          - 6
          - 7
          - 8
        archs:
          - noarch
          - x86_64
  tasks:
    # - name: Ensure file exists
    #   file:
    #     path: "{{ startup_hugepage_actions[os.stdout]['grub_path'] }}"
    #     state: touch
    #   ignore_errors: yes

    # - name: block_test
    #   blockinfile:
    #     path: "/home/hangzhou/hangz/ansible/testgrub.cfg"
    #     block: |
    #       djsafkldjfkla
    #     create: yes
    #     state: present
    #   register: kargs
    #   # delegate_to: localhost
    #   ignore_errors: yes
    # - debug:
    #     msg: "{{kargs}}"

    - name: download qat firmwares
      # get_url:
      #   url: "{{dlb_zip_url}}"
      #   dest: /usr/local/src
      #   mode: 0644
      #   force: yes 
      # ignore_errors: true
      # delegate_to: localhost
      shell: 
        cmd: |
          flock /tmp/dlb.lock bash -c '[ -e /usr/local/src/qatfirmware.tgz ] || curl --retry 5 -o /usr/local/src/qatfirmware.tgz {{ qat_firmware_repo }}'
        executable: /bin/bash
      ignore_errors: yes
      delegate_to: localhost

    - name: unzip qat firmwares
      unarchive:
        src: /usr/local/src/qatfirmware.tgz
        dest: /lib/firmware
        copy: yes
        mode: 0755
      ignore_errors: true


      
    - shell: |
        pwd
        ls -ahl






    

#     # - fail:
#     #     # msg: "This machine does not support dsa"
#     #     msg: "{{dsa_supported}}"
#     #   when: 1 = 1


    # - block:
    #   # - debug:
    #   #     msg: "{{item.key}} is {{item.value}}"
    #   #   loop: "{{ users | dict2items }}"

    #   # - shell:
    #   #     echo "{{item.key}} is {{item.value}}"
    #   #   loop: "{{ users | dict2items }}"
    #   #   register: p
    #   # - debug:
    #   #     var: p.msg
      # - shell: 
      #     cmd: |
      #       ls -ahl

      #   args:
      #     chdir: "/home/hangzhou/hangz/ansible-bios"
      #   ignore_errors: yes

# - hosts: localhost
#   tasks:
#     - name: create log file
#       debug:
#         msg: "no influence"   












  # - block:
  #   - name: set bios111111111111111
  #     shell: 
  #       cmd: echo 100000
  #       executable: /bin/bash
  #     # when: testpath1 is exists

  #   - debug:
  #         msg: "file exist"
  #   when: testpath is exists
  #   rescue:
  #     - shell:
  #         echo aaa


    # - name: set bios with given configuration
    #   shell: 
    #     cmd: echo 1000
    #     executable: /bin/bash
    #   register: P
    # - debug: 
    #     msg: "{{P}}"
    # - name: set bios with given configuration
    #   shell: 
    #     cmd: echo 10000
    #     executable: /bin/bash
    # delegate_to: localhost
    # tags: t1



      





      # insertafter: djsafkldjfkla
      # state: absent 


  # - name: test shell
  #   shell: 
  #     rm -rf  abc;
  #     cd ~;
  #     ls -ahl;
  #     ls dafsdfsadf;
  #     ls dfasf;
  #     pwd;
  #   register: return_va
  #   # delegate_to: localhost
  #   # failed_when: false
  #   ignore_errors: true
  #   tags: t1
  # - debug:
  #     msg: "{{return_va}}"





  # - name: Ansible check file exists.
  #   stat:
  #     # path: "/sys/bus/pci/drivers/vfio-pci"
  #     path: "{{ testpath }}"
  #   register: p
  
  # - debug:
  #     msg: "{{ p }}"

  # - name: aaaaarepo ##难道每次运行的时候必须重新进入,还真是，我服了这个老六
  #   shell: |
  #     echo "stat exist"
  #   when: p.stat.exists == false

  # - name: test 2
  #   shell:  echo "dafdf";ls dfasf;pwd
  #   register: return_va
  #   delegate_to: localhost
  #   failed_when: false
  #   tags: t2
  # - debug:
  #     msg: "{{return_va}}"




# ---

# - hosts: hangzhouvm
#   become: yes
#   gather_facts: no
#   tasks:
#   - debug:
#       msg: "index is {{item.0}} , value is {{item.1}}"
#     with_indexed_items: ['a','b','c']

#   - debug:
#       msg: "index is {{item.0}} , value is {{item.1}}"
#     loop: "{{ lookup('indexed_items',['a','b','c']) }}"




# - hosts: localhost
#   # remote_user: root
#   gather_facts: no
#   # tasks:
#   #   - debug:
#   #       var: hostvars.hangzhou_validation.shellreturn
#   #   - debug:
#   #       var: "{{hostvars.hangzhou_validation.testvar}}"
#   tasks:
#   - file:
#       path: "/test{{item}}"
#       state: absent
#     become: yes
#     with_sequence: start=2 end=10 stride=2




    # - shell: 
    #     cmd: |
    #       groupadd qat
    #       usermod -a -G qat `whoami`
    #       # sudo su -l $USER
    #       echo 1000

    #     executable: /bin/bash
    #   ignore_errors: true
    #   become: yes
    


# - hosts: ICX_junjunjie
#   remote_user: root
#   gather_facts: no
#   tasks:
#   - debug:
#       msg: "{{ansible_version}}"
#   - debug:
#       msg: "{{shellreturn}}"
#   - debug:
#       msg: "{{hostvars.hangzhouvm.shellreturn.stdout}}"



# - hosts: 10.166.31.106
#   gather_facts: yes
#   tasks:
#   - debug:
#       msg: "{{ ansible_os_family}}"
# - hosts: hangzhouvm
#   gather_facts: yes
#   tasks:
#   - debug:
#       msg: "{{ ansible_os_family}}"
# - hosts: ICX_junjunjie
#   gather_facts: yes
#   tasks:
#   - debug:
#       msg: "{{ ansible_os_family}}"
# - hosts: biostest
#   gather_facts: yes
#   tasks:
#   - debug:
#       msg: "{{ ansible_os_family}}"




